# Generated by Django 3.2.9 on 2021-11-28 15:15

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodel',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=django.core.files.storage.FileSystemStorage('media')),
        ),
    ]
