# Generated by Django 3.2.9 on 2021-11-28 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convapp', '0002_alter_filemodel_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodel',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
