# Generated by Django 3.2.9 on 2021-11-28 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convapp', '0003_alter_filemodel_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgmodel',
            name='img',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
